title: Yuyu Chen
position: PhD, ASA 
affiliation: University of Melbourne
email: yuyu.chen@unimelb.edu.au
keywords: Risk Aggregation
google_scholar: https://scholar.google.com.au/citations?user=0mhx91cAAAAJ&hl=en&oi=ao
#github_link: https://github.com/yaoyao-liu/minimal-light
#linkedin: https://www.linkedin.com/
avatar: ./assets/img/yu.jpeg
google_analytics: G-1D29G2JZ6D
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
#description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
#canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
